### ISSUE TITLE
bug:在项目运行一段时间后会报StackOverflowError

### ISSUE THREAD

**Issue by wangmeng3486** [dromara/forest#189]
在项目运行一段时间后会报StackOverflowError ，部分报错如下：
2024-01-04T13:46:46.690+08:00 ERROR 30 --- [io-8088-exec-11] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/portal/api] threw exception [Filter execution threw an exception] with root cause

java.lang.StackOverflowError: null
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]
	at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59) ~[forest-core-1.5.33.jar!/:1.5.33]

**Comment by victorsheng** [comment]
遇到了同样的错误

**Comment by LSauce** [comment]
遇到了同样的错误

**Comment by iwangbowen** [comment]
我也是

**Comment by kookx** [comment]
咋解决啊，也出现了

**Comment by witt-bit** [comment]
你们可以在运行时看下报错的那个接口的方法, 用arthas输出一下它`ForestMethod`的结构，找下`MappingTemplate.variableScope`属性, 这种情况应该是`VariableScope`的实例是`SubVariableScope`, 但其`parent`与`this`相等

**Comment by witt-bit** [comment]
> 咋解决啊，也出现了

给一个稳定复现的例子🌰

**Comment by kookx** [comment]
> > 咋解决啊，也出现了
> 
> 给一个稳定复现的例子🌰

起一个springboot-2.x程序，设置每几秒调用某接口查询数据，Forest使用声明式调用方式，JDK版本1.8，Forest版本1.5.36，运行几天后估计就会复现该问题
