### ISSUE TITLE
'DefaultAutoConverter' error:

### ISSUE THREAD

**Issue by 1050202387** [dromara/forest#192]
[Forest] Response: Status = 504, Time = 60031ms
com.dtflys.forest.exceptions.ForestHandlerException: com.dtflys.forest.exceptions.ForestConvertException: [Forest] auto converter: 'DefaultAutoConverter' error:
        at com.dtflys.forest.handler.ResultHandler.getResult(ResultHandler.java:156)
        at com.dtflys.forest.handler.ResultHandler.getResult(ResultHandler.java:44)
        at com.dtflys.forest.http.ResultGetter.get(ResultGetter.java:30)
        at com.dtflys.forest.http.ForestResponse.getResult(ForestResponse.java:367)
        at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleSyncWithException(MethodLifeCycleHandler.java:89)
        at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleSync(MethodLifeCycleHandler.java:55)
        at com.dtflys.forest.backend.ResponseHandler.handleSync(ResponseHandler.java:39)
        at com.dtflys.forest.backend.okhttp3.response.OkHttp3ResponseHandler.handleSync(OkHttp3ResponseHandler.java:29)
        at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:245)
        at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:279)
        at com.dtflys.forest.http.ForestRequest.execute(ForestRequest.java:4706)
        at com.dtflys.forest.reflection.ForestMethod.invoke(ForestMethod.java:1503)
        at com.dtflys.forest.proxy.InterfaceProxyHandler.invoke(InterfaceProxyHandler.java:236)
        at com.sun.proxy.$Proxy144.zfcgprocurementnotice(Unknown Source)
        at com.jr.datacenter.external.businesscode.hnJyTs.service.Firstorder.HnZfcgNoticePush.execute(HnZfcgNoticePush.java:194)
        at com.jr.datacenter.external.businesscode.hnJyTs.job.HnPublicResourceJob.HnPrJ(HnPublicResourceJob.java:111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)
Caused by: com.dtflys.forest.exceptions.ForestConvertException: [Forest] auto converter: 'DefaultAutoConverter' error:
        at com.dtflys.forest.converter.auto.DefaultAutoConverter.convertToJavaObject(DefaultAutoConverter.java:110)
        at com.dtflys.forest.handler.ResultHandler.getResult(ResultHandler.java:147)
        ... 21 more
Caused by: java.lang.NullPointerException
        at com.dtflys.forest.converter.auto.DefaultAutoConverter.tryConvert(DefaultAutoConverter.java:35)
        at com.dtflys.forest.converter.auto.DefaultAutoConverter.convertToJavaObject(DefaultAutoConverter.java:87)
        ... 22 more
这个是什么问题呢

**Comment by wzJun1** [comment]
+1
