### ISSUE TITLE
使用okhttp请求出现502，httpclient正常

### ISSUE THREAD

**Issue by SongSings** [dromara/forest#211]
forest version:1.5.33

bus-server 是本地host映射配置 
<img width="281" alt="image" src="https://github.com/user-attachments/assets/d411e98c-1ed5-4175-a1f4-c53e68c592e3">

okhttp 异常:
2024-11-01 14:42:41.081  INFO 96194 --- [67247860ab566b08a2e5359b] [  XNIO-1 task-1] c.d.forest.logging.DefaultLogHandler     : [Forest] Request (okhttp3): 
	GET http://bus-server:10003/wscrm-bus-api/group/info/selectPage?current=1&size=1&tenantId=83 HTTP
	Headers: 
		User-Agent: forest/1.5.33
		type: 2
		tenantId: 83
		Accept-Language: zh-CN
2024-11-01 14:43:03.203  WARN 96194 --- [] [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=47s83ms).
2024-11-01 14:43:03.210  INFO 96194 --- [] [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[192.168.1.3:10911] result: true
2024-11-01 14:43:03.210  INFO 96194 --- [] [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[192.168.1.3:10911] result: true
2024-11-01 14:43:03.212  INFO 96194 --- [] [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[192.168.1.3:10911] result: true
2024-11-01 14:43:03.212  INFO 96194 --- [] [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[192.168.1.3:10911] result: true
2024-11-01 14:43:03.217  INFO 96194 --- [67247860ab566b08a2e5359b] [  XNIO-1 task-1] c.d.forest.logging.DefaultLogHandler     : [Forest] Response: Status = 502, Time = 22126ms
2024-11-01 14:43:03.233 ERROR 96194 --- [67247860ab566b08a2e5359b] [  XNIO-1 task-1] s.a.w.e.r.GlobalHandlerExceptionResolver : 全局异常信息 ex=HTTP 502 ErrorContent=

com.dtflys.forest.exceptions.ForestNetworkException: HTTP 502 ErrorContent=
	at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleError(MethodLifeCycleHandler.java:153)
	at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleSyncWithException(MethodLifeCycleHandler.java:75)
	at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleSync(MethodLifeCycleHandler.java:55)
	at com.dtflys.forest.backend.ResponseHandler.handleSync(ResponseHandler.java:39)
	at com.dtflys.forest.backend.okhttp3.response.OkHttp3ResponseHandler.handleSync(OkHttp3ResponseHandler.java:29)
	at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:245)
	at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:279)
	at com.dtflys.forest.http.ForestRequest.execute(ForestRequest.java:4706)
	at com.dtflys.forest.reflection.ForestMethod.invoke(ForestMethod.java:1503)
	at com.dtflys.forest.proxy.InterfaceProxyHandler.invoke(InterfaceProxyHandler.java:236)
	at com.sun.proxy.$Proxy185.selectPage(Unknown Source)
<img width="1483" alt="image" src="https://github.com/user-attachments/assets/f8a659cc-3313-4785-9a46-ad9848597371">

httpclient 正常: 

2024-11-01 14:50:44.829  INFO 98177 --- [67247a44ab56cd418fb4feaf] [  XNIO-1 task-1] c.d.forest.config.ForestConfiguration    : [Forest] Http Backend: httpclient
2024-11-01 14:50:44.842  INFO 98177 --- [67247a44ab56cd418fb4feaf] [  XNIO-1 task-1] c.d.forest.logging.DefaultLogHandler     : [Forest] Request (httpclient): 
	GET http://bus-server:10003/wscrm-bus-api/group/info/selectPage?current=1&size=1&tenantId=83 HTTP
	Headers: 
		User-Agent: forest/1.5.33
		type: 2
		tenantId: 83
		Accept-Language: zh-CN
2024-11-01 14:50:44.906  INFO 98177 --- [67247a44ab56cd418fb4feaf] [  XNIO-1 task-1] c.d.forest.logging.DefaultLogHandler     : [Forest] Response: Status = 200, Time = 67ms
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/b06b3456-60f1-4cf8-974a-a5f942db950c">

**Comment by SongSings** [comment]
代理软件问题
