### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by lijingrs** [dromara/forest#212]
Caused by: java.lang.StackOverflowError: null
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)
        at com.dtflys.forest.mapping.SubVariableScope.getConfiguration(SubVariableScope.java:59)

**Comment by bytepoem** [comment]
有什么解决方案吗

**Comment by lijingrs** [comment]
> 有什么解决方案吗

use the old version
