### ISSUE TITLE
在普通项目中使用post请求会报错

### ISSUE THREAD

**Issue by testwangchao** [dromara/forest#26]
```java
package com.example.request;

import com.dtflys.forest.annotation.Body;
import com.dtflys.forest.annotation.Get;
import com.dtflys.forest.annotation.Post;


public interface Client {
    @Post(url = "http://127.0.0.1:8090/api/admin/login/precheck", contentType = "application/json")
    public String login(@Body("username") String username, @Body("password") String password);
}

```

```java
package com.example;

import com.dtflys.forest.config.ForestConfiguration;
import com.example.request.Client;

public class main {
    public static void main(String[] args) {
        Client myClient = ForestConfiguration.configuration().createInstance(Client.class);
        myClient.login("1sadsa@163.com", "123456789");
    }
}
```

运行报错:
```text
[main] INFO com.dtflys.forest.config.ForestConfiguration - [Forest] Http Backend: okhttp3
Exception in thread "main" java.lang.NullPointerException
	at com.dtflys.forest.backend.body.AbstractBodyBuilder.buildBody(AbstractBodyBuilder.java:151)
	at com.dtflys.forest.backend.okhttp3.executor.AbstractOkHttp3Executor.prepareBody(AbstractOkHttp3Executor.java:171)
	at com.dtflys.forest.backend.okhttp3.executor.AbstractOkHttp3Executor.execute(AbstractOkHttp3Executor.java:181)
	at com.dtflys.forest.backend.okhttp3.executor.AbstractOkHttp3Executor.execute(AbstractOkHttp3Executor.java:281)
	at com.dtflys.forest.http.ForestRequest.execute(ForestRequest.java:1608)
	at com.dtflys.forest.http.ForestRequest.execute(ForestRequest.java:1625)
	at com.dtflys.forest.reflection.ForestMethod.invoke(ForestMethod.java:1143)
	at com.dtflys.forest.proxy.InterfaceProxyHandler.invoke(InterfaceProxyHandler.java:121)
	at com.sun.proxy.$Proxy9.login(Unknown Source)
	at com.example.main.main(main.java:16)
```

**Comment by mySingleLive** [comment]
是不是没有添加 Fastjson 或 Jackson 等 JSON框架依赖？

**Comment by testwangchao** [comment]
这是我的依赖，需要fastjson和jackjson都安装吗？
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>forest-demo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.dtflys.forest</groupId>
            <artifactId>forest-core</artifactId>
            <version>1.5.0-RC4</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.21</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.14.9</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.11.2</version>
        </dependency>
    </dependencies>

</project>```

**Comment by testwangchao** [comment]
我换成fastjson是没问题的，不确定是不是jackson的版本问题
