### ISSUE TITLE
我不太懂，spring版本问题嘛

### ISSUE THREAD

**Issue by AlfredNing** [dromara/forest#84]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.dtflys.forest.springboot.ForestBeanRegister]: Factory method 'getForestBeanRegister' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.config.BeanDefinition.setRole(I)V
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
	... 41 more
Caused by: java.lang.NoSuchMethodError: org.springframework.beans.factory.config.BeanDefinition.setRole(I)V

**Comment by mySingleLive** [comment]
需要 spring 5.1 以上版本

**Comment by mySingleLive** [comment]
这个在 `1.5.22` 版本中解决了，可以兼容较低版本的 spring
